language: node_js
node_js:
  - lts/*
dist: bionic
os: linux
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
branches:
  only:
    - travis-ci

before_script:
  - npm i -g @angular/cli

script:
  - npm run lint
  - npm run test-headless
