language: node_js
node_js:
  - lts/*
dist: bionic
os: linux
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
branches:
  only:
    - travis-ci

before_script:
  - npm i -g @angular/cli

script:
  - npm run lint
  - npm run test-headless
  - npm run build -- --prod

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  local_dir: ./dist/angular-ci-demo
  on:
    branch: travis-ci
